### ISSUE TITLE
TODO 1.0

### ISSUE THREAD

**Issue by krzysiekpiasecki** [krzysiekpiasecki/Bowling#1]
Must have: 

- [ ] BowlingGameEvent
- [ ] BowlingRoll (Domain implementation of RollInterface)
- [ ] BowlingFrame (Domain implementation of FrameInterface)
- [x] BowlingGameInterface (Other Domain interfaces? Rather BowlingGameInterface)
- [x] SequenceInterface
- [x] PointSequenceInterface
- [x] RollInterface
- [x] RollSequenceInterface
- [x] Regenarate API
- [x] Renamespace project Bowling (Roll) / BowlingGame (BowlingRoll)
- [x] FrameInterface
- [x] FrameSequenceInterface
- [x] Use FrameSequence at  

Should have:

- [ ] Documentation
- [ ] UML Diagram
- [ ] Metrics
- [ ] Code coverage
- [ ] Run phan with Travis 
- [ ] Resize and optimize size of the main image
- [ ] Tests must ensure that new instances are returned

Could have:

- [ ] Document more exception on generic interfaces (ex. RollSequenceInterface::addRoll)
- [ ] Roll(int pins, int points) ?

Want have:

- [ ] Remove addSequenceInterace family from sequences and introduce new object for copying elements or allow it in a constructor.

Questions?

- [ ] Should be natural indexing of Rolls, Frames, ... Not Roll(0) but Roll(1) ?
- [ ] Allow only domain sequences in sequences?
- [ ] Remove ex. Frame:rollNumber  with Frame.rollSequence[number] etc.

LISKOV CHECKLIST

**Comment by krzysiekpiasecki** [comment]
Won't fix
